module.exports = {
  // List of channels to ignore
  ignoredChannel: ["215442075011907584"],
  // List of triggers
  trigger: [
    "69",
    "６９",
    "sixty *nine",
    "sixty-nine",
    "sixty 9",
    "六十九",
    "六九",
  ],
  // List of response (randomly chosen)
  response: [
    "Nice.",
    "Naisu.",
    "ナイス",
    "𝕹𝖎𝖈𝖊.",
    "𝓝𝓲𝓬𝓮.",
    "𝒩𝒾𝒸𝑒.",
    "ℕ𝕚𝕔𝕖.",
    "Ｎｉｃｅ．",
    "ɴɪᴄᴇ.",
    "˙ǝɔıN",
    "🄽🄸🄲🄴.",
    ".ɘɔiͶ",
    "🅽🅸🅲🅴.",
    "ₙᵢcₑ.",
    "ᴺⁱᶜᵉ.",
    "Ⓝⓘⓒⓔ.",
    "ภเςє.",
    "Nιƈҽ.",
    "ռɨƈɛ.",
    "ᏁᎥፈᏋ.",
    "ŋıƈɛ.",
    "ຖi¢ē.",
    "𝐍𝐢𝐜𝐞.",
    "𝘕𝘪𝘤𝘦.",
    "𝙉𝙞𝙘𝙚.",
    "𝙽𝚒𝚌𝚎.",
    "ПIᄃΣ.",
    "ηι¢є.",
    "ñï¢ê.",
    "₦ł₵Ɇ.",
    "【N】【i】【c】【e】【.】",
    "『N』『i』『c』『e』『.』",
    "░N░i░c░e░.░",
    "[̲̅N][̲̅i][̲̅c][̲̅e][̲̅.]",
    "ᑎIᑕE.",
    "N̾i̾c̾e̾.̾",
    "N͎i͎c͎e͎.͎",
    "N͓̽i͓̽c͓̽e͓̽.͓̽",
  ],
};
